name: Android Build CI

on:
  push:
    branches: [ "main", "workflow-testing" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write
  repository-projects: write
  contents: write
  issues: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Resources
      uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # need to cache dependencies etc.
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: |
        ./gradlew build --scan

    - name: Handle Push Events
      # handle push events
      if: ${{ failure() && github.event_name == 'push' && github.ref_name == 'workflow-testing' }}
      run: |
        export PUSH_DEPTH=$(git rev-list --count ${{ github.event.before }}..${{ github.event.after }}) &&
        git config --global user.name "Your Worklow... Probably" &&
        git config --global user.email "zsalgado3@gatech.edu" &&
        git branch failed-build_${{ github.event.before }}-${{ github.event.after }} &&
        git add -A &&
        git commit -m "Failed push for hash \n hash ${{ github.event.before }} through ${{ github.event.after }} \n <summary>" &&
        git push &&
        # git checkout main &&
        git checkout workflow-testing &&
        git reset --hard HEAD~$PUSH_DEPTH
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Handle PR Events
      # handle pull request events
      if: ${{ failure() && github.event_name == 'pull_request' }}
      run: |
        gh pr comment ${{ github.event.number }} --body <summary>

