name: Android Build CI

on:
  push:
    branches: [ "main", "workflow-testing" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write
  issues: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Resources
      uses: actions/checkout@v4

      # need to cache dependencies etc.
    - name: Setup Gradle 
      uses: gradle/actions/setup-gradle@v3

    - name: Build
      run: |
        ./gradlew build --scan

    - name: Handle Push Events
      # handle push events
      if: ${{ failure() && github.event_name == 'push' && github.ref_name == 'main' }}
      run: |
        export PUSH_DEPTH=$(git rev-list --count ${{ github.event.before }}..${{ github.event.after }}) &&
        git config --global user.name 'Github Workflow' &&
        git branch failed-build_${{ github.event.before }}-${{ github.event.after }} &&
        git add -A &&
        git commit -m "Failed push for hash \n hash ${{ github.event.before }} through ${{ github.event.after }} \n <summary>" &&
        git push &&
        git checkout main &&
        git reset --hard HEAD~$PUSH_DEPTH

    - name: Handle PR Events
      # handle pull request events
      if: ${{ failure() && github.event_name == 'pull_request' }}
      run: |
        gh pr comment ${{ github.event.number }} --body <summary>

